sudo: required
services:
  - docker

script:
  - docker build -t ricardohan93/likeiam5-api .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ricardohan/likeiam5-api
