version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password

  pgadmin4:
    hostname: pgadmin4
    image: dpage/pgadmin4
    ports:
      - 6003:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "ricardoshhan@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "chokitos1234"
    depends_on:
      - postgres

  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - DOMAIN=http://localhost:3000/
      - CLIENT=http://localhost:8080/
      - JWT_SECRET=klfoaifieh773da
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - 3000:3000
    depends_on:
      - postgres
